### ISSUE TITLE
How to write custom rules ?  I have to define my own rules to check code.  Please explain how to write ?

### ISSUE THREAD

**Issue by nagur** [fortitudetec/sonar-ruby-plugin#10]

**Comment by chrisrohr** [comment]
I will have to look but that may be an outstanding issue at the moment.  Also I was told that SonarQube itself is coming out with their own Ruby analyzer soon. At that point this plugin will be deprecated.

**Comment by chrisrohr** [comment]
@nagur Were you able to upgrade your version of SonarQube to 7.4+?  Please let me know if you still need this feature.

**Comment by sleberknight** [comment]
Closing as we are archiving this project
