### ISSUE TITLE
Getting an error while running with SonarQube 7.3

### ISSUE THREAD

**Issue by Ali-Shaikh** [fortitudetec/sonar-ruby-plugin#13]
ERROR: Error during SonarQube Scanner execution
ERROR: com.fortitudetec.sonar.plugins.ruby.rubocop.RubocopSensor has unsatisfied dependency 'class com.fortitudetec.sonar.plugins.ruby.rubocop.RubocopParser' for constructor 'public com.fortitudetec.sonar.plugins.ruby.rubocop.RubocopSensor(com.fortitudetec.sonar.plugins.ruby.PathResolver,com.fortitudetec.sonar.plugins.ruby.rubocop.RubocopExecutor,com.fortitudetec.sonar.plugins.ruby.rubocop.RubocopParser)' from org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer@3e58d65e:269<[Immutable]:org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer@6c6c5427:262<[Immutable]:org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer@6ed3f258:9<[Immutable]:org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer@6cd45b6c:52<|
ERROR:

Any idea what this error is about?

**Comment by chrisrohr** [comment]
Are you running SonarQube with Java 9+?

**Comment by Ali-Shaikh** [comment]
@chrisrohr No, Java 8
java.runtime.version | 1.8.0_181-b13

**Comment by hnioche** [comment]
I have the exact same issue with SonarQube 7.3
I'm running this version of Java on both the build agent that run the scanner and the server hosting SonarQube:
```
java -version
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-8u181-b13-0ubuntu0.16.04.1-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)
```

**Comment by hnioche** [comment]
I was able to make a custom build of the plugin work.
For the rubocop sensor and combined result sensor, the constructor dependency injection fails to inject any custom class from the plugin. It injects properly classes from sonar APIs.

The plugin does run once I switched dependency injection of those classes to creating the instances in the sensors constructor.

I'm not sure it's the proper solution though....

**Comment by chrisrohr** [comment]
@hnioche Thank you for looking into that.  Do you want to submit a PR for this and I can review the change?

**Comment by mmeintker-tc** [comment]
Same issue here:

`
Community EditionVersion 7.3 (build 15553)

java -version
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-8u181-b13-1~deb9u1-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)
`

Thanks for looking into it.

**Comment by chrisrohr** [comment]
@Ali-Shaikh, @mmeintker-tc and @hnioche Were you able to get this working? Also, just an FYI, that as of SonarQube 7.4, they have built their own Ruby analyzer plugin, so this plugin is deprecated.  Please let me know if you still need this worked.

**Comment by mmeintker-tc** [comment]
Thanks, running new version of Sonarqube solved the problem.

**Comment by chrisrohr** [comment]
:+1:
