### ISSUE TITLE
Simplecov sensor ignores sonar.projectBaseDir

### ISSUE THREAD

**Issue by mafavale** [fortitudetec/sonar-ruby-plugin#14]
When running sonar-scanner from a different folder than the current project and using the **sonar.projectBaseDir** from the running directory the simple cov sensor does not detect the reportPath file which was configured relatively.

Example project:
/workspace
-----> /project
-----------> /coverage
--------------> /.resultset.json
Steps to reproduce:
1) Go to working directory /workspace
2) Run command `sonar-scanner -Dsonar.projectBaseDir=project -Dsonar.verbose=true`
3) Look at the output: Coverage file is not detected and error logged: 

> java.io.FileNotFoundException: File 'coverage/.resultset.json' does not exist
> 	at org.apache.commons.io.FileUtils.openInputStream(FileUtils.java:299)
> 	at org.apache.commons.io.FileUtils.readFileToString(FileUtils.java:1711)
> 	at org.apache.commons.io.FileUtils.readFileToString(FileUtils.java:1734)
> 	at com.fortitudetec.sonar.plugins.ruby.simplecov.SimpleCovParser.parseResultsFile(SimpleCovParser.java:73)
> 	at com.fortitudetec.sonar.plugins.ruby.simplecov.SimpleCovParser.parse(SimpleCovParser.java:39)
> 	at com.fortitudetec.sonar.plugins.ruby.simplecov.SimpleCovSensor.execute(SimpleCovSensor.java:31)
> 	at com.fortitudetec.sonar.plugins.ruby.metrics.CombinedCoverageSensor.execute(CombinedCoverageSensor.java:28)
> 	at org.sonar.scanner.sensor.SensorWrapper.analyse(SensorWrapper.java:53)
> 	at org.sonar.scanner.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:88)
> 	at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:82)
> 	at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:68)

**Comment by chrisrohr** [comment]
@mafavale Thank you for your ticket.  What version of SonarQube are you using?  The reason I ask is that as of SonarQube 7.4, the Sonar team has built their own Ruby analyzer into SonarQube.  Because of that, this plugin is deprecated.  If you are stuck on 7.3, I can try to figure out what is going on here.

**Comment by mafavale** [comment]
Oh I see, I am using SonarQube 7.1 and the Jenkins scanner plugin version 3.3.0. I think we are upgrading soon, but not sure when.

**Comment by chrisrohr** [comment]
If you need to be here for longer term, I can try to see about tracking down a fix.

**Comment by mafavale** [comment]
I have workaround the problem for the moment, i guess that gives me time until sonarqube is updated, so i really don't need a fix right now.

**Comment by sleberknight** [comment]
Closing as we are archiving this project
