### ISSUE TITLE
readme is not expressive

### ISSUE THREAD

**Issue by prakhar345** [fortitudetec/sonar-ruby-plugin#3]
I am not able to integrate my ruby on rails project with sonarqube using this plugin

**Comment by tygrash** [comment]
same here. would be great if you could elaborate the steps to integrate it and send the results to sonarqube @chrisrohr

**Comment by chrisrohr** [comment]
Thank you. I will update the README as soon as I can.

**Comment by chrisrohr** [comment]
@prakhar345 and @tygrash I have updated the README with some instructions.  Please try them and let me know if that works for you. Once I hear from you I will close this ticket.

Thanks

**Comment by Romack** [comment]
So I think I am missing something... does this plugin use the rules that are configured within SonarQube?

**Comment by chrisrohr** [comment]
@Romack As of right now, the plugin creates the ruleset based on the Rubocop file in src/main/resources.  I'm pretty sure that I left that file as the default ruleset from rubocop.  If I get sometime (or someone wants to submit a PR for it), then it would be great to figure out how to update the ruleset based on a custom definition for your project.
