### ISSUE TITLE
Need the JAR file 

### ISSUE THREAD

**Issue by ParthBarot-BoTreeConsulting** [fortitudetec/sonar-ruby-plugin#4]
I want to use this plugin, README says "Download the JAR file" but it does not have it. Can you please share the steps to generate the JAR file successfully? I am getting long list of errors while trying to build this using maven on my ubuntu.

**Comment by chrisrohr** [comment]
@ParthBarot-BoTreeConsulting Sorry for the delayed response, I had my notification settings wrong.  You can find the download on the releases page: https://github.com/fortitudetec/sonar-ruby-plugin/releases.

As for building it, if you send me the errors I can try to help troubleshoot was it going wrong.

**Comment by chrisrohr** [comment]
I'm going to close this for now, feel free to reopen if you are having problems.
