### ISSUE TITLE
Rubocop reported issues against a file that isn't in the analysis set - will be ignored

### ISSUE THREAD

**Issue by daguero** [fortitudetec/sonar-ruby-plugin#5]
I have sonarqube 6.7.1 and sonar-sacner with rubocop 0.56.0 installed.

sonar-project.properties:
sonar.projectKey=111
sonar.sources=/mnt
sonar.cpd.exclusions=/mnt/coverage/**,/mnt/tmp/**
sonar.exclusions=**/images/**,**/assets/fonts/**

sonar.ruby.file.suffixes=rb,ruby
#sonar.ruby.coverage.reportPath=/mnt/coverage/spec/.resultset.json
sonar.ruby.rubocopConfig=/mnt/.rubocop_sonar.yml
sonar.ruby.rubocop=/usr/bin/rubocop
sonar.ruby.rubocop.reportPath=/mnt/rubocop-result.json
sonar.ruby.rubocop.filePath=/mnt

Any ideas???

**Comment by chrisrohr** [comment]
@daguero Sorry for the delayed response, as my notification settings were incorrect.

Are you saying you received issues against files in the exclusions list?  Did the issues show up in Rubocop or in Sonar or both?

**Comment by chrisrohr** [comment]
I'm going to close this for now, if you are still having issues, please reopen.
