### ISSUE TITLE
Marketplace

### ISSUE THREAD

**Issue by vassilevsky** [fortitudetec/sonar-ruby-plugin#6]
Hi :)

Creating this for tracking progress with the Marketplace listing.

Any interested people can watch this issue.

Please let me know if I can help with something.

**Comment by chrisrohr** [comment]
@vassilevsky Thank you.  Yes I will need to figure out the process.  If you have experience in doing this, by all means I would love help in setting this up.

**Comment by vassilevsky** [comment]
No, I have no idea. But I saw this TODO item in the README and thought that it would be great.

Google gave me this:

https://docs.sonarqube.org/display/DEV/Deploying+to+the+Marketplace

Unmet requirements from this document:
- [ ] Release notes
- [ ] Description (a more thorough one)
- [ ] Test environment / project for SonarSource staff
- [ ] Add this repo to SonarCloud and make sure it's green

This seems to be totally doable so you have a very high chance of success!

I can help you with anything Ruby-related, and with technical writing. But I can't code Java confidently.

Please let me know how I can help.

**Comment by chrisrohr** [comment]
@vassilevsky Any thoughts on what the SonarSource staff would be looking for for the "test environment"?  Looking at a number of projects on the plugin page, the repos don't have anything but the source.  Do you think I need to provide a ruby "app"?

**Comment by chrisrohr** [comment]
I think I have everything added to the project that would be needed to request inclusion.

I have only tested this plugin up to SonarQube version 6.5.  I think I need to do an analysis of this in 7.x before I submit.  I will try to do that this week.

**Comment by chrisrohr** [comment]
Marketplace request submitted: https://community.sonarsource.com/t/new-release-ruby-plugin/1906

Release v1.1.0 has been cut

**Comment by chrisrohr** [comment]
Well, good news and bad news.

Bad news: This plugin was rejected from being included into the marketplace

Good news: SonarSource is coming out with their own Ruby analyzer (apparently in the next few weeks)

I'm going to close this ticket.  I will maintain this plugin until the official one from them comes out.  I don't think there is anything in this plugin extra to what they are doing as they are building in the ability to import rubocop and simplecov results.
